### ISSUE TITLE
The bottom of the typewriter text and its drop shadow are clipping out

### ISSUE THREAD

**Issue by UbnGithub** [SpectrixOfficial/SpectrumDevs.github.io#3]
![Picture of the text clipping out](https://i.imgur.com/hjRCPS2.png)
As you can see in this screenshot, the bottom of the text, and it's drop shadow, are both clipping out.

**Comment by notBanii** [comment]
**o o f**

**Comment by KittyTigerWolf** [comment]
_**O O F**_

**Comment by SpectrixOfficial** [comment]
This might be a problem with the custom font. I'll see what I can do

**Comment by SpectrixOfficial** [comment]
I'm no longer working on this website so...
